using Microsoft.AspNet.Identity.EntityFramework;
using MyCashFlow.Domains.Artificial;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MyCashFlow.Domains.DataObject
{
	[Table("User", Schema = "Configuration")]
	public class User : IdentityUser
	{
		#region Primary key
		
		// Already generated by Identity framework

		#endregion

		#region Standard fields

		[Required]
		[Index(IsUnique = true)]
		[StringLength(128)]
		public override string UserName { get; set; }
		
		public Gender Gender { get; set; }

		[Display(Name = "First name")]
		public string FirstName { get; set; }

		[Display(Name = "Middle name")]
		public string MiddleName { get; set; }

		[Display(Name = "Last name")]
		public string LastName { get; set; }

		#endregion

		#region Foreign keys

		//[Display(Name = "Country")]
		//public short CountryID { get; set; }

		public int? AddressID { get; set; }

		public int? ContactID { get; set; }

		public virtual Country Country { get; set; }
		public virtual Address Address { get; set; }
		public virtual Contact Contact { get; set; }

		#endregion
	}
}
