using Microsoft.AspNet.Identity.EntityFramework;
using MyCashFlow.Domains.Artificial;
using MyCashFlow.Domains.Identity;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace MyCashFlow.Domains.DataObject
{
	[Table("User", Schema = "Configuration")]
	public class User : IdentityUser<int, CustomUserLogin, CustomUserRole, CustomUserClaim>
	{
		#region Primary key
		
		// Already generated by Identity framework

		#endregion

		#region Standard fields

		[Required]
		[Index(IsUnique = true)]
		[StringLength(128)]
		public override string UserName { get; set; }
		
		public Gender Gender { get; set; }
		
		public string FirstName { get; set; }
		
		public string MiddleName { get; set; }
		
		public string LastName { get; set; }

		#endregion

		#region Foreign keys
		
		public short CountryID { get; set; }

		public int? AddressID { get; set; }

		public int? ContactID { get; set; }

		public virtual Country Country { get; set; }
		public virtual Address Address { get; set; }
		public virtual Contact Contact { get; set; }

		#endregion
	}
}
